<?php

namespace app\modules\admin\forms;

use app\models\AuthItems;
use yii\rbac\Role;


class RoleForm extends AuthItems
{
	/**
	 * @var string
	 */
	public $allow_permissions;

	/**
	 * @var string
	 */
	public $deny_permissions;

	public $role;

	public $permissions;

	public $scenario = 'add-role';


	/**
	 * @inheritdoc
	 * @return array
	 */
	public function rules()
	{
		return array_merge(parent::rules(), [
			[['allow_permissions', 'deny_permissions', 'permissions'], 'safe'],
		]);
	}


	public function beforeValidate()
	{
//		$this->on($this->scenario == 'add-role',
//			function (){return $this->type = Role::TYPE_ROLE;
//		});

		$this->type = Role::TYPE_ROLE;
		$this->permissions = explode(',', $this->allow_permissions);
		return parent::beforeValidate(); // TODO: Change the autogenerated stub
	}

}